apiVersion: v1
kind: Pod
metadata:
  name: app-redinessprob
  namespace: demo
spec:
  containers:
    - name: app
      image: gcr.io/k8s-k3s/demo:v1.0.0
      ports:
        - containerPort: 8000
      readinessProbe:
        httpGet:
          path: /ready
          port: 8000
        initialDelaySeconds: 10
        timeoutSeconds: 5
      livenessProbe:
        httpGet:
          path: /
          port: 8000
        initialDelaySeconds: 15
        timeoutSeconds: 10
      volumeMounts:
        - name: data
          mountPath: /data
  volumes:
    - name: data
      hostPath:
        path: /var/lib/app